# Generated by Django 5.0.1 on 2024-01-31 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voetbalspelers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datum_invoer',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='datum_wijziging',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
