# Generated by Django 5.0.1 on 2024-01-31 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voetbalspelers', '0002_alter_post_datum_invoer_alter_post_datum_wijziging'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='auteur_naam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voetbalspeler_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
